// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkkir9AyDg2NyCMLXIhDGMcJfNdndA9lk',
    appId: '1:47935554618:web:9c746f35a6ee2506a52103',
    messagingSenderId: '47935554618',
    projectId: 'tabarrocars',
    authDomain: 'tabarrocars.firebaseapp.com',
    storageBucket: 'tabarrocars.firebasestorage.app',
    measurementId: 'G-JKQVYRX1RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZaMXzMxcVoQnaEhz22JL5eRQB55xk4Vw',
    appId: '1:47935554618:android:605d89b2ea4cbf68a52103',
    messagingSenderId: '47935554618',
    projectId: 'tabarrocars',
    storageBucket: 'tabarrocars.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzA4cWMbjN7KJnpKBT4t-VCai-0K65VyI',
    appId: '1:47935554618:ios:43fe3bab2ee23408a52103',
    messagingSenderId: '47935554618',
    projectId: 'tabarrocars',
    storageBucket: 'tabarrocars.firebasestorage.app',
    iosBundleId: 'com.example.tabarrocars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzA4cWMbjN7KJnpKBT4t-VCai-0K65VyI',
    appId: '1:47935554618:ios:43fe3bab2ee23408a52103',
    messagingSenderId: '47935554618',
    projectId: 'tabarrocars',
    storageBucket: 'tabarrocars.firebasestorage.app',
    iosBundleId: 'com.example.tabarrocars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkkir9AyDg2NyCMLXIhDGMcJfNdndA9lk',
    appId: '1:47935554618:web:ab7c1e75bcf121c5a52103',
    messagingSenderId: '47935554618',
    projectId: 'tabarrocars',
    authDomain: 'tabarrocars.firebaseapp.com',
    storageBucket: 'tabarrocars.firebasestorage.app',
    measurementId: 'G-9PYHKTEK0J',
  );
}
